### ISSUE TITLE
Broken as of a few days ago.

### ISSUE THREAD

**Issue by WildGenius** [terrygonguet/sub-to-yt-playlist#1]
No tabs load, not even settings. Great idea for an extension, incidentally!

**Comment by terrygonguet** [comment]
Hi, thanks for the report 😊

I'm aware this extensionisn't very stable because of the variability of the data returned by the YT API. 

Did the extension work properly before ?

I'm very sorry but I don't have a lot of time to fix this and it still works for me 😅 Any contribution is welcome though, the code isn't complex 😉

I'll try to make it more resilient whenever I have time.

**Comment by WildGenius** [comment]
Worked beautifully until the time of the report. In case it matters, the browser that has the issue is Brave (not sure whether Chrome's privileged access to google accounts factors into this somehow).
    In my opinion, the extension deserves a lot more exposure for what it does, so I'm sorry to hear you can't spend a lot of time on it.

**Comment by ballo** [comment]
Does anyone have a screen shot of how this is supposed to work? I'm surprised this doesn't have a million downvotes on the store given the complete lack of any documentation whatsoever.

**Comment by terrygonguet** [comment]
@ballo There are a few screenshots on the [Chrome store page](https://chromewebstore.google.com/detail/subscribe-to-youtube-play/iiidhbnhammhbfmaigembfdlmaeabgfl) but it's moot because, as you've probably noticed, the exension is broken.

I'd love to have millions of downvotes, it would indicate strong interest in what is mostly a public version of a tool I made for myself 👍

Anyway I should have more time to re-do this quite soon so it can be functional enough to get those downvotes!

**Comment by ballo** [comment]
Would this help?
https://www.reddit.com/user/ConceptsShining/comments/1846anm/guide_how_to_see_when_videos_were_added_to_a/

**Comment by terrygonguet** [comment]
> Would this help? https://www.reddit.com/user/ConceptsShining/comments/1846anm/guide_how_to_see_when_videos_were_added_to_a/

It might, thanks for the link!

Not sure I'll be able to use it as-is because of implementation details but it's nice to know that there is at least one way to get that data.

Anyway I still haven't been had time to fix this extension and now it's broken for me too :(
